### ISSUE TITLE
Namespace trouble when Formatter was change.

### ISSUE THREAD

**Issue by reverse-cat** [rmrevin/yii2-changelog#5]
I have custom class for Formatter
// common/config/main
'formatter' => [
            'class' => 'common\components\CustomFormatter',
// [ ... ] ,
// end config
And after install this package i had UnknownClassException everytime when try to do console command ( like yii migrate )

I think problem in /resource/Log.php at line 41
$Formatter= \Yii::$app->get('formatter');

Full stack trace below
root@www:/var/www/html# php yii hello // try to do hello world in console
Hello World!
`<?`
namespace common\components;

class CustomFormatter extends \yii\i18n\Formatter
{
    public function asPhone($num) //custom method
    {
        // method code
    }
}
`?>`Exception 'yii\base\UnknownClassException' with message 'Unable to find 'common\components\CustomFormatter' in file: /var/www/html/common/components/CustomFormatter.php. Namespace missing?'

in /var/www/html/vendor/yiisoft/yii2/BaseYii.php:296

Stack trace:
#0 [internal function]: yii\BaseYii::autoload('common\\componen...')
#1 [internal function]: spl_autoload_call('common\\componen...')
#2 /var/www/html/vendor/yiisoft/yii2/di/Container.php(426): ReflectionClass->__construct('common\\componen...')
#3 /var/www/html/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('common\\componen...')
#4 /var/www/html/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('common\\componen...', Array, Array)
#5 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('common\\componen...', Array, Array)
#6 /var/www/html/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#7 /var/www/html/vendor/yiisoft/yii2/base/Module.php(724): yii\di\ServiceLocator->get('formatter', true)
#8 /var/www/html/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('formatter')
#9 /var/www/html/vendor/rmrevin/yii2-changelog/resources/Log.php(41): yii\di\ServiceLocator->__get('formatter')
#10 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(108): rmrevin\yii\changelog\resources\Log->init()
#11 [internal function]: yii\base\BaseObject->__construct(Array)
#12 /var/www/html/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array)
#13 /var/www/html/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('rmrevin\\yii\\cha...', Array, Array)
#14 /var/www/html/vendor/yiisoft/yii2/di/Instance.php(119): yii\di\Container->get('rmrevin\\yii\\cha...', Array, Array)
#15 /var/www/html/vendor/rmrevin/yii2-changelog/components/LogsStorage.php(46): yii\di\Instance::ensure(Array)
#16 /var/www/html/vendor/rmrevin/yii2-changelog/Bootstrap.php(32): rmrevin\yii\changelog\components\LogsStorage::save()
#17 [internal function]: rmrevin\yii\changelog\Bootstrap->rmrevin\yii\changelog\{closure}(Object(yii\base\Event))
#18 /var/www/html/vendor/yiisoft/yii2/base/Component.php(557): call_user_func(Object(Closure), Object(yii\base\Event))
#19 /var/www/html/vendor/yiisoft/yii2/base/Application.php(389): yii\base\Component->trigger('afterRequest')
#20 /var/www/html/yii(27): yii\base\Application->run()
#21 {main}

**Comment by reverse-cat** [comment]
Я изначально предлагал заменить $Formatter= \Yii::$app->get('formatter'); на  new \yii\i18n\Formatter;
Но в таком случае игнорируются настройки из конфига.
Поэтому даже не знаю, что здесь делать.

**Comment by reverse-cat** [comment]
Забыл сказать, что этот баг я наблюдаю только в консоли. На бекенде всё работает нормально.

**Comment by reverse-cat** [comment]
Это так тупо, но ошибка в моём классе заключалась в том что файл открывался коротким способом и namespace в консоли терялся.
У меня в модели было
`<?`
`namespace ##`
Вместо богоподобного
`<?php`
`namespace`
Из-за символа новой строки консольный обработчик терял namespace
