### ISSUE TITLE
Error in migration

### ISSUE THREAD

**Issue by zickkeen** [rmrevin/yii2-changelog#6]
```
create table {{%changelog}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1286 Unknown storage engine 'ARCHIVE'
The SQL being executed was: CREATE TABLE `changelog` (
        `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `action` int(11),
        `entity_type` varchar(255),
        `entity_id` varchar(255),
        `present` varchar(255),
        `changes` blob,
        `env` blob,
        `created_at` int(11),
        `updated_at` int(11)
) CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=ARCHIVE (/app/vendor/yiisoft/yii2/db/Schema.php:677)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `c...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('CREATE TABLE `c...')
#2 /app/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /app/vendor/rmrevin/yii2-changelog/migrations/m150816_130733_changelog.php(23): yii\db\Migration->createTable('{{%changelog}}', Array, 'CHARACTER SET u...')
#4 /app/vendor/yiisoft/yii2/db/Migration.php(114): m150816_130733_changelog->safeUp()
#5 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(727): yii\db\Migration->up()
#6 /app/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m150816_130733_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#8 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /app/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#10 /app/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('', Array)
#11 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#12 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#13 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#14 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /app/yii(20): yii\base\Application->run()
#16 {main}
*** failed to apply m150816_130733_changelog (time: 0.003s)


0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.
```

### Database Server Spesification
Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.1.45-MariaDB-cll-lve - MariaDB Server
Protocol version: 10
Server charset: cp1252 West European (latin1)

**Comment by rmrevin** [comment]
@zickkeen Your database doesn't support `ARCHIVE` engine. Use a different table engine.
